### ISSUE TITLE
Transaction reply map type

### ISSUE THREAD

**Issue by gorhawk** [CyberSource/cybersource-sdk-java#114]
https://github.com/CyberSource/cybersource-sdk-java/blob/d7ea22362fd26eafa5693c33b9e4c8262cf1d542/java/src/main/java/com/cybersource/ws/client/Client.java#L162

If we know here that the returned type is Map<String, String>, why not change the return type of the function? This causes all kinds of "unchecked" type warnings, even in this code it's suppressed with an annotation.

**Comment by mahendya1002** [comment]
we will do it in 6.2.10
