### ISSUE TITLE
Support for Akamai Sureroute?

### ISSUE THREAD

**Issue by lkb2k** [CyberSource/cybersource-sdk-java#16]
Hi,  

According to communications from cybersource, we should be updating our endpoints from  
 ics2wstest.ic3.com/ics2ws.ic3.com ->  ics2wstesta.ic3.com/ics2wsa.ic3.com

Is that planned to be added to this SDK directly?  Or should we be overriding the serverURL property somehow in our own code when calling the SDK?

**Comment by aaronblenkush** [comment]
Add one of the following lines to your cybs.properties:

    serverURL=https://ics2wstesta.ic3.com/commerce/1.x/transactionProcessor
    serverURL=https://ics2wsa.ic3.com/commerce/1.x/transactionProcessor

**Comment by amie-gao** [comment]
the issue has been addressed in release v6.2.1
