### ISSUE TITLE
Mention "_has_escapes" in the README

### ISSUE THREAD

**Issue by tiporan** [CyberSource/cybersource-sdk-java#21]
Guys,

I've been troubleshooting the SDK because when using NVP Request with strings in UTF-8 special chars, like "José" in the billTo_firstName, I was receiving an error as below:

![image](https://cloud.githubusercontent.com/assets/1115173/14260008/ca96132a-fa7f-11e5-8bad-be79e73ab161.png)

Debugging all the code, I just discovered this happened because the message was transformed in order to deal with HTML/XML escape special chars.

I was wondering if you guys could mention the existance of the key "_has_escapes" in the README of this project just like you guys did in the Utility.java. 

After reading this comment in the Utility.java, just added the key into my requestMap (HashMap) and everything worked fine!

Adding this mechanism in the README probably would save some time for someone in the future. This is specially true for developers working with customers in countries where the mother language has very special chars, like Portuguese.

Just my 2 cents. Loved the SDK.

**Comment by LeifW** [comment]
Looks like it's calling `StringEscapeUtils.escapeHtml()` in Apache commons-lang. There's an `.escapeXml()` method in there that'd probably be more appropriate if you're turning around and parsing that with Xerces.

**Comment by LeifW** [comment]
The text ends up as the body of an XML element - the only characters required to be escaped in there are `<`, `>`, and `&`.

**Comment by LeifW** [comment]
The text ends up as the body of an XML element - the only characters required to be escaped in there are `<`, `>`, and `&`.
