### ISSUE TITLE
Receiving:  Payment processor error This field is invalid or missing.

### ISSUE THREAD

**Issue by alex-fernandez** [CyberSource/cybersource-sdk-java#28]
This had worked previously but now we are receiving this error, anyone who could help?
Payment processor error This field is invalid or missing. Please contact customer support.: merchant_id 

ccAuthReply_reasonCode=150
requestID=4667236970366429001015
requestToken=Ahj77wSR+gXZQO8arupuypb1c4SvwClvVzhK/aQN2AMD4AGkmW6QHaUmAJyP0C7KB3jVd1NwsXRZ
reasonCode=150

**Comment by amie-gao** [comment]
Please kindly contact cybersource support in this regarding.

**Comment by aqabawe** [comment]
@alex-fernandez Did you manage to solve this?

**Comment by alex-fernandez** [comment]
Hi, I already solved the issue, its more than a year ago. I move on

**Comment by aqabawe** [comment]
In case this would help someone in the future. I was getting a `Payment processor error This field is invalid or missing. Please contact customer support.: merchant_id` on our Ruby implementation of Secure Acceptance.

The reason turned out to be that we were using a currency that was not supported by our account.

**Comment by medjabir** [comment]
The error reporting of Cybersrouce is very confusing..

@aqabawe Thank you a lot, your suggestion really saved me a lot of time.

**Comment by vimarshacooray** [comment]
> The error reporting of Cybersrouce is very confusing..
> 
> @aqabawe Thank you a lot, your suggestion really saved me a lot of time.

Confusing is an understatement, their entire document and source is all over the place.

**Comment by kaidenBH** [comment]
> In case this would help someone in the future. I was getting a `Payment processor error This field is invalid or missing. Please contact customer support.: merchant_id` on our Ruby implementation of Secure Acceptance.
> 
> The reason turned out to be that we were using a currency that was not supported by our account.

Im from the future and it did help a lot, Thanks.
