### ISSUE TITLE
CyberSource payment processor error: Unsupported currency

### ISSUE THREAD

**Issue by zonorion** [CyberSource/cybersource-sdk-java#39]
I am supposed to integrate a CyberSource payment gateway:
My request data :
`request.put( "ccAuthService_run", "true" );
request.put( "ccCaptureService_run", "true" );
request.put( "merchantReferenceCode", "your_merchant_reference_code" ); 
request.put( "billTo_firstName", "John" );
request.put( "card_accountNumber", "4111111111111111" );
request.put( "card_expirationMonth", "12" );
request.put( "card_expirationYear", "2020" );
request.put( "purchaseTotals_currency", "USD" );
request.put("purchaseTotals_grandTotalAmount", "100.00");`

I am always getting this error response:
`decision=REJECT
invalidField_0=purchaseTotals_currency
ccAuthReply_avsCode=2
reasonCode=102
merchantReferenceCode=your_merchant_reference_code
invalidField_=purchaseTotals_currency`

It looks like my merchant ID is not configured with a valid currency. Please help me.

**Comment by amie-gao** [comment]
Please kindly contact Cybersource merchant support to troubleshoot the request. Thanks.
