### ISSUE TITLE
Error while trying to process a refund. 

### ISSUE THREAD

**Issue by pavanbl13** [CyberSource/cybersource-sdk-java#40]
Hi,
I`m trying to send a refund request and I`m getting XML parse error. Could anyone please help me on this.  Below is the xml request. 

Thanks

**Comment by pavanbl13** [comment]
`<requestMessage xmlns="urn:schemas-cybersource-com:transaction-data-1.126">
<merchantID>fujixerox_au</merchantID>
<merchantReferenceCode>MRC-123</merchantReferenceCode>
<purchaseTotals>
<grandTotalAmount>121.65</grandTotalAmount>
<currency>AUD</currency>
</purchaseTotals>
<ccCreditService run="true">
	<captureRequestID>4720858171836945501018</captureRequestID>
</ccCreditService>
</requestMessage>`

**Comment by amie-gao** [comment]
Please kindly contact CYBS merchant support to troubleshoot the request. Thanks.
