### ISSUE TITLE
Security key subject DN does not match what SDK code expects.

### ISSUE THREAD

**Issue by PeterMDF** [CyberSource/cybersource-sdk-java#61]
Hello,

Their is not much activity here but I thought I would give this a shot.

I am implementing the CyberSource Simple Order API and have run into a strange issue regarding the generated security key and how the SDK parses information within it.

On the business center using a test account a .p12 security key was generated successfully.

When using the security key with the SDK the following error occurs (merchant id replaced with zeros):

`Exception while obtaining private key from KeyStore with alias, '000000000000'`

After some debugging it seems like this error happens because the subject DN provided in the security key does not match what the SDK code thinks should be there. This is what the subject DN looks like in the security key (serial number replaced with zeros):

`CN=CyberSource_SJC_US,SN=0000000000000000000000`

But if you look at the Identity class in the SDK, it seems like it wants to find "SERIALNUMBER=" instead of the "SN=" provided in the security key itself:

```
private void setUpServer() throws SignException {
 if (serialNumber == null && x509Cert != null) {
	 String subjectDN = x509Cert.getSubjectDN().getName();
	 if (subjectDN != null) {
		 String subjectDNrray[] = subjectDN.split("SERIALNUMBER=");
		 if (subjectDNrray.length == 1 && subjectDNrray[0].contains("CyberSourceCertAuth")){
			 name = keyAlias = "CyberSourceCertAuth";
		 }
		 else if (subjectDNrray.length == 2 && subjectDNrray[0].contains(SERVER_ALIAS)) {
			 name = SERVER_ALIAS;
			 serialNumber = subjectDNrray[1]; 
			 keyAlias = "serialNumber=" + serialNumber + ",CN=" + name;
		 }else{
			 throw new SignException("Exception while obtaining private key from KeyStore with alias, '" + merchantConfig.getKeyAlias() + "'");
		 }

	 } else {
		 throw new SignException("Exception while obtaining private key from KeyStore with alias, '" + merchantConfig.getKeyAlias() + "'");
	 }
}
```

See also the code here:

https://github.com/CyberSource/cybersource-sdk-java/blob/master/java/src/main/java/com/cybersource/ws/client/Identity.java#L93

This ends up throwing the SignException, which stops the transaction from happening.

Do you have any insight on what is going wrong? Is there something I am not doing correctly?

Thank you.

**Comment by jeaton-visa** [comment]
Hello Peter, Sorry for your trouble.

It looks like you are setting the "sender" (the party responsible for signing the message) with the id of "CyberSource_SJC_US". That id is in fact the recipient of the message and there is no private key associated with that id within the p12 file.

The "sender" of the message is the merchant you logged into the business center with. 

Check your client configuration and confirm you are using the correct merchant_id and possible "sender_id" in your configuration and/or message.

Best wishes.

**Comment by PeterMDF** [comment]
Hello jeaton,

I am very sorry for using this issue tracker for technical support and I am very grateful for any assistance you can provide.

I have searched through the documentation and through the code and I do not see anywhere where I can set a "sender".

I have confirmed that I am using the proper merchant_id but do not see anywhere in the code or in the documentation where I can set a "sender_id".

I do notice though in the SDK code in the SecurityUtil class the readAndStoreCertificateAndPrivateKey method is looping over multiple aliases found within the .p12 key.

Enumeration enumKeyStore = merchantKeyStore.aliases();

I have the proper keyAlias set in the merchant config but since there are multiple aliases, if the loop happens to hit the "CyberSource_SJC_US" alias first it tries to create an Identity with it and fails due to the above mentioned "SERIALNUMBER" issue...

Could this be an issue with how the security key was generated? I was not the one who has access to generate keys, they are being generated by a client.

The documentation I am looking at is: http://apps.cybersource.com/library/documentation/dev_guides/Simple_Order_API_Clients/Client_SDK_SO_API.pdf

I apologize if I am not making much sense.

Thank you again for your help.

**Comment by PeterMDF** [comment]
I have figured out the issue and it is on my end. I am sorry for wasting your time with this.

The reason was that the system we are integrating the SDK into already had a dependency on the BouncyCastle cryptography provider (bcprov-jdk14) and the CyberSource SDK has a dependency on version 1.5 (bcprov-jdk15).

The BouncyCastle developers changed how the subject DN string is built. Basically, instead of using the string "SN=" they have switched to using "SERIALNUMBER=".

The CyberSource SDK has hard coded the string "SERIALNUMBER=" in the Identity class and when it is not found in the subject DN, throws an error.

Maybe a way around this hard coded string should be found in the future so that the dependency on BouncyCastle versions would be more relaxed. They could decide to change this string in the future as well making upgrading the dependencies of the CyberSource SDK more difficult.

I apologize for wasting your time with this issue and thank you again for your help.
