### ISSUE TITLE
error constructing MAC: unknown parameter type.

### ISSUE THREAD

**Issue by marcomontani** [CyberSource/cybersource-sdk-java#89]
Hi, 
I am trying to use the client within the wildfly 10.X application server. I included the client using Gradle:
compile ("com.cybersource:cybersource-sdk-java:6.2.4")

At the first attempt of usage, it told me that the BouncyCastleProvider could not be found.
I added the Jar to the lib/ext folder of my JDK, then modified the java.security configuration file adding bouncycastle as a provider and when i restarted the error changed in 

15:07:50,849 ERROR [stderr] (default task-2) com.cybersource.ws.client.ClientException: error constructing MAC: java.security.InvalidAlgorithmParameterException: unknown parameter type.
15:07:50,849 ERROR [stderr] (default task-2) 	at com.cybersource.ws.client.Client.runTransaction(Client.java:132)
15:07:50,849 ERROR [stderr] (default task-2) 	at com.cybersource.ws.client.Client.runTransaction(Client.java:68)

Activating the logs with the library very little was added:
2017-09-16 15:33:58.771 default task-3 INFO     > Client, End of soapWrap   16ms
2017-09-16 16:24:44.405 default task-3 EXCEPTION> Exception while loading KeyStore, 'null'
2017-09-16 16:24:44.405 default task-3 EXCEPTION> 
ClientException details:
innerException: 
java.io.IOException: error constructing MAC: java.security.InvalidAlgorithmParameterException: unknown parameter type.
	at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at com.cybersource.ws.client.SecurityUtil.readAndStoreCertificateAndPrivateKey(SecurityUtil.java:111)
	at com.cybersource.ws.client.SecurityUtil.loadMerchantP12File(SecurityUtil.java:88)
	at com.cybersource.ws.client.Client.soapWrapAndSign(Client.java:194)
	at com.cybersource.ws.client.Client.runTransaction(Client.java:112)
	at com.cybersource.ws.client.Client.runTransaction(Client.java:68)

Could you please help me understand where is the problem?

Thanks

[EDIT]
I don't know if this helps, but switching to the more recent bouncycastle version (1.58), the error becomes:
16:22:09,522 ERROR [stderr] (default task-2) com.cybersource.ws.client.ClientException: error constructing MAC: java.security.InvalidAlgorithmParameterException: inappropriate parameter type: javax.crypto.spec.PBEParameterSpec

**Comment by schuller007** [comment]
Have you resolved this in any way? I am also encountering running on java 1.7 on a Windows machine.

**Comment by RDornian** [comment]
Working with @schuller007, we were able to find a workable solution. First we tried your suggestion of switching the bouncycastle to the latest version and then decided to try and deal with that same issue you came up with (inappropriate parameter type: javax.crypto.spec.PBEParameterSpec). From here I found this article https://stackoverflow.com/questions/44585976/bouncycastle-problems-multiple-webapps-in-one-tomcat which talks about the possible issue arising from housing multiple webapps within a single Tomcat. We decided to break up our local webapps into multiple Tomcats, which unfortunately was not an option for the author of that article. After that we weren't experiencing any issues and so I reduced the bouncy castle version back to its original value in the cybersource-sdk-java and continued to have no issues. Hopefully this helps and you aren't in similar situation as the aforementioned author.

**Comment by marcomontani** [comment]
Sorry for the late response.
Using the wildfly application server, i found out i had to ad the bouncycastle library as a module in the application server and not copying it in the lib/ext forlder.

**Comment by pts-danielmanley** [comment]
I tried a hack of SecurityUtil with a main() method to load my merchant p12 file and it works:
```
    public static void main(String[] argv) throws Exception {
        KeyStore merchantKeyStore;
        try {
            merchantKeyStore = KeyStore.getInstance(KEY_FILE_TYPE,
                                                    bcProvider);
        } catch (KeyStoreException e) {
            System.out.println("Exception while instantiating KeyStore");
            throw new SignException(e);
        }
        
        String keyFilename = "/config/pgw/dev/ejbProperties/cybersource/globaltestaccount.p12";
        try {
            System.out.println("loading the merchantKeyStore using ["+merchantKeyStore.getClass().getName()+"]");
            merchantKeyStore.load(new FileInputStream(keyFilename),
                                  "globaltestaccount".toCharArray());
        } catch (IOException e) {
            System.out.println("Exception while loading KeyStore, '" + keyFilename + "'");
            throw new SignException(e);
        } catch (NoSuchAlgorithmException e) {
            System.out.println("Exception while loading KeyStore, '" + keyFilename + "'");
            throw new SignException(e);
        } catch (CertificateException e) {
            System.out.println("Exception while loading KeyStore, '" + keyFilename + "'");
            throw new SignException(e);
        }
        
        System.out.println("aliases ["+merchantKeyStore.aliases()+"]");
    }
```

```
[daniel.manley@pts-dmanley2 tmp]$ $JAVA_HOME/bin/java -cp .:bcprov-jdk15on-1.54.jar:wss4j-1.6.19.jar:cybersource-sdk-java.jar com.cybersource.ws.client.SecurityUtilDan
loading the merchantKeyStore using [java.security.KeyStore]
aliases [java.util.Hashtable$Enumerator@46ab18da]
```
so it's gotta be a security provider that Wildfly is adding in front of the stuff the bcprov like causing the exception I'm encountering eh?  (I also swapped out the wss4j 1.6.17 module for the desired 1.6.19 and still doesn't work in wildfly)

**Comment by RDornian** [comment]
We solved this issue by copying the bcprov-jdk15on-1.54.jar into our jre\lib\ext folder
